interface/interface/urls.py
from django.contrib import admin
from django.urls import path, include

from run_model import views

urlpatterns = [
    path('', views.home, name='home'),
    path('run_chain/', include("run_chain.urls")),
    path('run_model/', include("run_model.urls")),
    path('admin/', admin.site.urls),
    path("repo_info/", views.repo, name="repo")
]

interface/run_chain/urls.py
from django.urls import path

from . import views

app_name = "run_chain"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:model_id>/", views.run, name="run"),
]

interface/run_model/urls.py
from django.urls import path

from . import views

app_name = "run_model"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:model_id>/", views.run, name="run"),
]

interface/run_chain/models.py
from django.db import models

# Create your models here.

interface/run_model/models.py
from django.db import models

# Create your models here.

interface/run_chain/views.py
import datetime
import os
import sys
from glob import glob

import yaml
from django.shortcuts import render

PY_FILE_DIR = os.path.abspath(os.path.dirname(__file__))
PY_ROOT_DIR = os.path.abspath(os.path.join(PY_FILE_DIR, ".."))
PY_REPO_DIR = os.path.dirname(PY_ROOT_DIR)
CONFIG_DIR = r"config/model_config/model_chains"

sys.path.append(os.path.join(PY_REPO_DIR, "src"))
from framework.model_chain import ModelChain


def index(request):
    path = os.path.join(PY_REPO_DIR, CONFIG_DIR)
    configs = [file
               for p, subdir, files in os.walk(path)
               for file in glob(os.path.join(p, "*.yml"))]

    model_info = []
    for num, item in enumerate(configs):
        with open(item, "r") as file:
            params = yaml.safe_load(file)

            model_info += [{'index': num + 1,
                            'config_file': os.path.split(item)[-1],
                            'models_in_chain': params['models'].keys()}]

    return render(request, "run_chain/index.html", {'configs': model_info})


def run(request, model_id):
    path = os.path.join(PY_REPO_DIR, CONFIG_DIR)
    path = [file
            for p, subdir, files in os.walk(path)
            for file in glob(os.path.join(p, "*.yml")) if model_id == os.path.split(file)[-1][:-4]][0]

    model_logs = run_chain(path, request)

    return render(request, "run_chain/run.html",
                  context={'model_id': model_id, 'model_logs': model_logs})


def run_chain(path, request):
    model_chain = ModelChain(path)

    model_chain.run_chain()

    # Get model logs for each model in the chain
    with open(path, 'r') as file:
        config = yaml.safe_load(file)['models']

    model_logs = {}
    for key, val in config.items():
        with open(os.path.join(PY_REPO_DIR, val['config']), 'r') as file:
            log_info = yaml.safe_load(file)['parameters']['model_parameters']

        log_name = log_info['log_name']
        if '{date}' in log_name:
            log_name = log_name.format(date=datetime.date.today())

        with open(os.path.join(PY_REPO_DIR, log_info['log_location'], log_name) + ".log", 'r') as file:
            logs = file.read().splitlines()

        model_logs[key] = logs

    return model_logs

interface/run_model/views.py
import datetime
import importlib
import os
import sys
from glob import glob

import markdown
import yaml
from django.contrib import messages
from django.shortcuts import render

PY_FILE_DIR = os.path.abspath(os.path.dirname(__file__))
PY_ROOT_DIR = os.path.abspath(os.path.join(PY_FILE_DIR, ".."))
PY_REPO_DIR = os.path.dirname(PY_ROOT_DIR)
CONFIG_DIR = r"config/model_config/model_metadata"

sys.path.append(os.path.join(PY_REPO_DIR, "src"))
sys.path.append(PY_REPO_DIR)
from framework.model_wrapper import DeployWrapper


def home(request):
    return render(request, "run_model/home.html")


def repo(request):
    with open(os.path.join(PY_REPO_DIR, "README.md"), 'r') as f:
        markdown_string = f.read()
    readme_html = markdown.markdown(markdown_string)

    return render(request, "run_model/repo.html", {'readme_txt': readme_html})


def index(request):
    path = os.path.join(PY_REPO_DIR, CONFIG_DIR)
    configs = [file
               for p, subdir, files in os.walk(path)
               for file in glob(os.path.join(p, "*.yml"))]

    model_info = []
    for num, item in enumerate(configs):
        with open(item, "r") as file:
            params = yaml.safe_load(file)['config']

        model_info += [{'index': num + 1,
                        'config_file': os.path.split(item)[-1],
                        'model_id': params['model_id'],
                        'model_type': params['model_type'],
                        'type': params['type']}]

    return render(request, "run_model/index.html", {'configs': model_info})


def run(request, model_id):
    path = os.path.join(PY_REPO_DIR, CONFIG_DIR)
    path = [file
            for p, subdir, files in os.walk(path)
            for file in glob(os.path.join(p, "*.yml")) if model_id == os.path.split(file)[-1][:-4]][0]

    run_model(request, path)

    return render(request, "run_model/run.html", context={'model_id': model_id})


def run_model(request, path: str):
    with open(path, 'r') as file:
        config = yaml.safe_load(file)['config']

    DeployWrapper(get_model_class(config), config['sys_config'],
                  config['model_config']).run_model()

    with open(os.path.join(PY_REPO_DIR, config['model_config'])) as file:
        config = yaml.safe_load(file)['parameters']['model_parameters']

    log_name = config['log_name']
    if '{date}' in log_name:
        log_name = log_name.format(date=datetime.date.today())

    with open(os.path.join(PY_REPO_DIR, config['log_location'], log_name) + ".log", 'r') as file:
        logs = file.read().splitlines()

    for line in logs:
        messages.add_message(request, messages.INFO, line)


def get_model_class(model_config: dict):
    model_class = getattr(importlib.import_module(model_config['model_path']), model_config['model'])
    return model_class

interface/interface/templates/base.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>Model Hub</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
            integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
            crossorigin="anonymous"></script>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <meta name="theme-color" content="#7952b3">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
    </style>

</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <img src="{% static 'company_logo.png' %}" width="35" height="35" margin-right="10px">

            <li class="nav-item">
                <a class="navbar-brand" href="{% url 'home' %}">Model Hub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </li>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto w-100 justify-content-left">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'run_model:index' %}">Run Model</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="{% url 'run_chain:index' %}">Run Model Chain</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="{% url 'repo' %}">More Information</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<footer class="text-muted py-5">
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                    <svg class="bi" width="30" height="24">
                        <use xlink:href="#bootstrap"></use>
                    </svg>
                </a>
                <span class="mb-3 mb-md-0 text-body-secondary">© EY</span>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-body-secondary" href="https://github.com/hledwards33/python-template">
                    <svg class="bi" width="24" height="24">
                        <img src="https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png" width="40"
                             height="40"></svg>
                </a></li>
            </ul>
        </footer>
    </div>
</footer>


</body>
</html>

interface/run_chain/templates/run_chain/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<main>

    <div class="py-5 text-center">

        <h2>Model Chain Configurations</h2>
        <p class="lead">The below list contains all the possible model chain configurations available to run.</p>
    </div>

    <table class="table caption-top" border="1">
        <caption></caption>
        <thead>
        <tr>
            <th scope="col">Index</th>
            <th scope="col">Config File</th>
            <th scope="col">Models in Chain</th>
        </tr>
        </thead>
        <tbody>
        {% for item in configs %}
        <tr>
            <th scope="row">{{item.index}}</th>
            <td><a href="{% url 'run_chain:run' item.config_file|slice:-4 %}">{{item.config_file}}</td>
            <td>
                <table class="table mb-0 table-bordered" border="1">
                    {% for model in item.models_in_chain %}
                    <tr>
                        <th>
                            {{model}}
                        </th>
                    </tr>
                    {% endfor %}
                </table>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


</main>


{% endblock %}

interface/run_chain/templates/run_chain/run.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<main>
    <div class="py-5 text-center">

        <h2>Model Chain Platform</h2>
        <p class="lead">You are running the following model chain configuration <b>{{model_id}}</b>.</p>
    </div>


    <div class="py-5 text-left">
        <h3 align="center">Model Logs</h3>
        <br>
        <div class="card shadow-sm">
            <div class="card-body">
                {% for model, logs in model_logs.items %}
                <h4>Logs for {{model}}</h4>
                <br>
                <ul class="messages">

                    <table class="table table-striped table-hover table-bordered" border="2">
                        <caption></caption>
                        <thead>
                        <tr>
                            <th scope="col">Message</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for message in logs %}
                        <tr>
                            <td>{{ message }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </ul>
                {% endfor %}
            </div>
        </div>

    </div>


</main>

{% endblock %}

interface/run_model/templates/run_model/home.html
{% load static %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>


<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
</head>


<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
<meta name="generator" content="Hugo 0.122.0">
<title>Cover Template · Bootstrap v5.3</title>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">


<!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<meta name="theme-color" content="#712cf9">


<style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
</style>


<!-- Custom styles for this template -->
<link href="cover.css" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-bg-dark">
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="cover-container d-flex w-200 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <img src="{% static 'company_logo.png' %}" width="45" height="45">
            <h3 class="float-md-start mb-0">Model Hub</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link fw-bold py-1 px-3" href="run_model/">Run Model</a>
                <a class="nav-link fw-bold py-1 px-0" href="run_chain/">Run Model Chain</a>
            </nav>
        </div>
    </header>

    <main class="px-3">
        <h1>Welcome to your Model Hub.</h1>
        <p class="lead">To get started select a link in the navigation bar above, or to learn more about the model
            repository click below to view the repository README file.</p>
        <p class="lead">
            <a href="repo_info/" class="btn btn-lg btn-light fw-bold border-white bg-white">Learn more</a>
        </p>
    </main>

    <footer class="mt-auto text-white-50">
        <p></p>
    </footer>
</div>


</body>
</html>

interface/run_model/templates/run_model/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<main>

    <div class="py-5 text-center">

        <h2>Model Configurations</h2>
        <p class="lead">The below list contains all the possible model configurations available to run.</p>
    </div>

    <table class="table caption-top">
        <caption></caption>
        <thead>
        <tr>
            <th scope="col">Index</th>
            <th scope="col">Config File</th>
            <th scope="col">Model ID</th>
            <th scope="col">Model Type</th>
            <th scope="col">Type</th>
        </tr>
        </thead>
        <tbody>
        {% for item in configs %}
        <tr>
            <th scope="row">{{item.index}}</th>
            <td><a href="{% url 'run_model:run' item.config_file|slice:-4 %}">{{item.config_file}}</td>
            <td>{{item.model_id}}</td>
            <td>{{item.model_type}}</td>
            <td>{{item.type}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


</main>


{% endblock %}

interface/run_model/templates/run_model/repo.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<main>
    <div class="py-5 text-center">

        <h2>Repository Information</h2>
        <p class="lead">Below is the README.md file from the python repository supporting your Model Hub.</p>
    </div>

    <div class="card shadow-sm" align="left">
        <div class="card-body">
                {% autoescape off %}
                {{readme_txt}}
                {% endautoescape %}
        </div>
    </div>


</main>


{% endblock %}

interface/run_model/templates/run_model/run.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<main>
    <div class="py-5 text-center">

        <h2>Model Platform</h2>
        <p class="lead">You are running the following model configuration <b>{{model_id}}</b>.</p>
    </div>


    <div class="py-5 text-left">
        <h3 align="center">Model Logs</h3>
        <br>
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="lead">{% if messages %}
                <ul class="messages">

                    <table class="table table-striped table-hover table-bordered" border="2">
                        <caption></caption>
                        <thead>
                        <tr>
                            <th scope="col">Message</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for message in messages %}
                        <tr>
                            <td>{{ message }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </ul>
                {% endif %}
            </div>
        </div>
    </div>


</main>

{% endblock %}